import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.ai': 'Cutscene AI',
    'hero.badge': 'Innovate, Create, Elevate',
    'hero.title1': 'Want to learn',
    'hero.title2': 'video editing',
    'hero.title3': 'is your solution',
    'hero.subtitle': 'Join our growing community of over 330 students and transform your career with our premium, hands-on curriculum designed for the modern world.',
    'hero.explore': 'Explore Courses',
    'hero.studentsWork': 'Our Students Work',
    'stats.students': 'Students',
    'stats.courses': 'Courses',
    'stats.workshops': 'Free Workshops',
    'stats.certified': 'Certified',
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Your portal to make a change.',
    'courses.seeAll': 'See all courses',
    'courses.details': 'Details',
    'courses.getStarted': 'Get Started',
    'studentsWork.title': 'Students Work',
    'studentsWork.subtitle': 'Witness the incredible transformations. Our students go from beginners to professional creators.',
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Track your learning journey and manage your content.',
    'dashboard.enrolled': 'Enrolled',
    'dashboard.certificates': 'Certificates',
    'dashboard.yourCourses': 'Your Courses',
    'dashboard.continue': 'Continue',
    'dashboard.progress': 'Course Progress',
    'dashboard.completedLessons': 'Completed Lessons',
    'dashboard.uploadTitle': 'Upload Project Video',
    'dashboard.uploadPlaceholder': 'Video Title (e.g. Chapter 1 Homework)',
    'dashboard.uploadBtn': 'Select Video File',
    'dashboard.uploading': 'Uploading...',
    'dashboard.latestActivity': 'Latest Activity',
    'dashboard.streak': 'Learning Streak',
    'dashboard.days': 'Days in a row',
    'dashboard.weeklyGoal': 'Weekly Goal',
    'dashboard.noActivity': 'No recent activity found.',
    'dashboard.noEnrollments': "You haven't enrolled in any courses yet.",
    'dashboard.browse': 'Browse Courses',
    'dashboard.certTitle': 'Certificates',
    'dashboard.certEarned': 'Course Completed',
    'dashboard.viewCert': 'View Certificate',
    'dashboard.noCert': 'Complete a course to earn your first certificate!',
    'course.level': 'Level',
    'course.duration': 'Duration',
    'course.learn': "What you'll learn",
    'course.requirements': 'Requirements',
    'course.curriculum': 'Course Curriculum',
    'course.instructor': 'Your Instructor',
    'course.lastUpdated': 'Last Updated',
    'course.reviews': 'Student Reviews',
    'course.writeReview': 'Write a Review',
    'course.rating': 'Rating',
    'course.submitReview': 'Submit Review',
    'course.noReviews': 'No reviews yet. Be the first to share your experience!',
    'course.locked': 'This content is locked. Please enroll in the course to access it.',
    'payment.title': 'Complete your order',
    'payment.subtitle': 'Join 330+ students already learning with us.',
    'payment.summary': 'Order Summary',
    'payment.total': 'Total Amount',
    'payment.method': 'Payment Method',
    'payment.pay': 'Pay',
    'payment.secure': 'Secure encrypted transaction',
    'payment.infoTitle': 'Student Information',
    'payment.infoSubtitle': 'Please provide your details for enrollment.',
    'payment.phone': 'Phone Number',
    'payment.phonePlaceholder': 'e.g. 0550 00 00 00',
    'payment.format': 'Course Format',
    'payment.recorded': 'Recorded (Self-paced)',
    'payment.online': 'Online (Live Sessions)',
    'payment.onlineExtra': '+2,000 DA',
    'payment.startDate': 'Starting Date',
    'payment.next': 'Continue to Payment',
    'payment.back': 'Back to Information',
    'video.homework': 'Homework Submission',
    'video.aiMentor': 'AI Mentor',
    'video.uploadHomework': 'Upload Homework',
    'video.chatPlaceholder': 'Ask your AI mentor about this lesson...',
    'video.markComplete': 'Mark as Complete',
    'video.completed': 'Completed',
    'video.next': 'Next Lesson',
    'course.back': 'Back to Course',
    'course.lockedTitle': 'This Content is Locked',
    'course.lockedDesc': 'Enroll in this course to unlock all chapters, exercises, and homework assignments.',
    'course.unlock': 'Unlock Course Now',
    'course.videoContent': 'Video content for Chapter',
    'course.markComplete': 'Mark as Complete',
    'course.markedComplete': 'Lesson marked as complete!',
    'course.about': 'About this',
    'course.task': 'Task',
    'course.expectedOutcome': 'Expected Outcome',
    'course.lessonDesc': 'In this lesson, we will dive deep into the core concepts of Chapter',
    'course.submitWork': 'Submit Your Work',
    'course.upload': 'Click or Drag to Upload Video',
    'course.needHelp': 'Need Help?',
    'course.helpDesc': 'Stuck on an exercise or have a question about the homework? Our mentors are here to help.',
    'course.contactSupport': 'Contact Support',
    'course.session': 'Session',
    'course.exercise': 'Exercise',
    'course.homework': 'Homework',
    'course.resources': 'Resources',
    'ai.welcome': "Hello! I'm your AI mentor. Upload your homework video, and I'll review it and give you an evaluation!",
    'ai.received': "Great! I've received your video. Give me a moment to review it...",
    'ai.mentor': 'AI Mentor',
    'ai.online': 'Online & Ready to Review',
    'ai.ask': 'Ask your mentor...',
    'ai.title': 'Cutscene AI',
    'ai.subtitle': 'Your all-in-one AI companion for video editing.',
    'ai.chat': 'Chat',
    'ai.voice': 'Voice',
    'ai.generate': 'Generate',
    'ai.image': 'Image',
    'ai.video': 'Video',
    'ai.music': 'Music',
    'ai.uploadDoc': 'Upload Document',
    'ai.placeholder': 'Ask anything about video editing...',
    'ai.systemPrompt': 'You are Cutscene AI, a specialized assistant for video editing and motion design. You are energetic, fun, and use emojis frequently! 🎬✨\n\nSTRICT RULES:\n1. TOPIC LIMIT: Only discuss video editing, motion design, cinematography, and post-production. Redirect other topics politely. 🎥\n2. NSFW: Strictly NO NSFW/18+ content. 🚫\n3. ALGERIAN DIALECT: Use Algerian Darja if appropriate. 🇩🇿\n4. ASSET GENERATION: If the user asks to "generate an image" or "generate a video", interpret this as a command to use your generation tools. 🖼️📹\n5. FORMATTING: Use Markdown for formatting. Use **bold** for emphasis. 📝\n6. PARAGRAPHS: You MUST use double newlines (\\n\\n) between every 2-3 sentences to create clear paragraphs. Never send a single giant block of text. 📑\n7. RTL/ARABIC: Respect RTL flow for Arabic. 🌍\n8. EDUCATION: Always suggest learning at "Cutscene Courses" when asked about learning or how to improve skills. Mention specific courses like "Cinematic Masterclass" or "Motion Design Pro". 🎓\n9. NAVIGATION SHORTCUTS: Suggest navigation buttons using [BUTTON: Label | Path]. For example: [BUTTON: Explore Courses | /courses]. 🚀',
    'auth.welcomeBack': 'Welcome back',
    'auth.enterDetails': 'Please enter your details to sign in',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.signIn': 'Sign in',
    'auth.orContinueWith': 'Or continue with',
    'auth.noAccount': "Don't have an account?",
    'auth.signUpFree': 'Sign up for free',
    'support.center': 'Support Center',
    'support.title': 'How can we help?',
    'support.desc': 'Our support team is here to help you with any questions or issues you may have. Reach out to us through any of the channels below.',
    'support.emailTitle': 'Email Support',
    'support.emailDesc': 'For general inquiries and billing questions.',
    'support.emailAction': 'Send Email',
    'support.whatsappTitle': 'WhatsApp Support',
    'support.whatsappDesc': 'Get quick answers to your technical questions.',
    'support.whatsappAction': 'Chat Now',
    'support.phoneTitle': 'Phone Support',
    'support.phoneDesc': 'Available Sunday to Thursday, 9am - 5pm.',
    'support.phoneAction': 'Call Us',
    'support.sendMessage': 'Send us a message',
    'support.formDesc': 'Have a specific question or feedback? Fill out the form and our team will get back to you within 24 hours.',
    'support.feature1': 'Expert technical support',
    'support.feature2': 'Quick response times',
    'support.fullName': 'Full Name',
    'support.namePlaceholder': 'Your name',
    'support.emailAddress': 'Email Address',
    'support.emailPlaceholder': 'Your email',
    'support.message': 'Message',
    'support.messagePlaceholder': 'How can we help?',
    'support.send': 'Send Message',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account settings and personal information.',
    'profile.personalInfo': 'Personal Information',
    'profile.displayName': 'Display Name',
    'profile.email': 'Email Address',
    'profile.password': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.updateBtn': 'Update Profile',
    'profile.updating': 'Updating...',
    'profile.success': 'Profile updated successfully!',
    'profile.error': 'Failed to update profile.',
    'profile.avatarTitle': 'Profile Picture',
    'profile.uploadAvatar': 'Upload New Picture',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.courses': 'Cours',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Tableau de bord',
    'nav.profile': 'Profil',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.ai': 'IA Cutscene',
    'hero.badge': 'Innover, Créer, Élever',
    'hero.title1': 'Envie d\'apprendre le',
    'hero.title2': 'montage vidéo',
    'hero.title3': 'est votre solution',
    'hero.subtitle': 'Rejoignez notre communauté de plus de 330 étudiants et transformez votre carrière avec notre programme premium conçu pour le monde moderne.',
    'hero.explore': 'Explorer les cours',
    'hero.studentsWork': 'Travaux des étudiants',
    'stats.students': 'Étudiants',
    'stats.courses': 'Cours',
    'stats.workshops': 'Ateliers gratuits',
    'stats.certified': 'Certifié',
    'courses.title': 'Nos Cours',
    'courses.subtitle': 'Votre portail pour changer.',
    'courses.seeAll': 'Voir tous les cours',
    'courses.details': 'Détails',
    'courses.getStarted': 'Commencer',
    'studentsWork.title': 'Travaux des Étudiants',
    'studentsWork.subtitle': 'Témoignez des transformations incroyables. Nos étudiants passent de débutants à créateurs professionnels.',
    'dashboard.welcome': 'Bon retour',
    'dashboard.subtitle': 'Suivez votre parcours d\'apprentissage et gérez votre contenu.',
    'dashboard.enrolled': 'Inscrit',
    'dashboard.certificates': 'Certificats',
    'dashboard.yourCourses': 'Vos Cours',
    'dashboard.continue': 'Continuer',
    'dashboard.progress': 'Progression du cours',
    'dashboard.completedLessons': 'Leçons terminées',
    'dashboard.uploadTitle': 'Télécharger la vidéo du projet',
    'dashboard.uploadPlaceholder': 'Titre de la vidéo (ex: Devoir Chapitre 1)',
    'dashboard.uploadBtn': 'Sélectionner un fichier vidéo',
    'dashboard.uploading': 'Téléchargement...',
    'dashboard.latestActivity': 'Activité récente',
    'dashboard.streak': 'Série d\'apprentissage',
    'dashboard.days': 'Jours consécutifs',
    'dashboard.weeklyGoal': 'Objectif hebdomadaire',
    'dashboard.noActivity': 'Aucune activité récente trouvée.',
    'dashboard.noEnrollments': "Vous n'êtes inscrit à aucun cours pour le moment.",
    'dashboard.browse': 'Parcourir les cours',
    'dashboard.certTitle': 'Certificats',
    'dashboard.certEarned': 'Cours terminé',
    'dashboard.viewCert': 'Voir le certificat',
    'dashboard.noCert': 'Terminez un cours pour obtenir votre premier certificat !',
    'course.level': 'Niveau',
    'course.duration': 'Durée',
    'course.learn': 'Ce que vous apprendrez',
    'course.requirements': 'Prérequis',
    'course.curriculum': 'Programme du cours',
    'course.instructor': 'Votre instructeur',
    'course.lastUpdated': 'Dernière mise à jour',
    'course.reviews': 'Avis des étudiants',
    'course.writeReview': 'Écrire un avis',
    'course.rating': 'Note',
    'course.submitReview': 'Envoyer l\'avis',
    'course.noReviews': 'Pas encore d\'avis. Soyez le premier à partager votre expérience !',
    'course.locked': 'Ce contenu est verrouillé. Veuillez vous inscrire au cours pour y accéder.',
    'payment.title': 'Finalisez votre commande',
    'payment.subtitle': 'Rejoignez plus de 330 étudiants qui apprennent déjà avec nous.',
    'payment.summary': 'Résumé de la commande',
    'payment.total': 'Montant total',
    'payment.method': 'Mode de paiement',
    'payment.pay': 'Payer',
    'payment.secure': 'Transaction sécurisée et cryptée',
    'payment.infoTitle': 'Informations sur l\'étudiant',
    'payment.infoSubtitle': 'Veuillez fournir vos coordonnées pour l\'inscription.',
    'payment.phone': 'Numéro de téléphone',
    'payment.phonePlaceholder': 'ex: 0550 00 00 00',
    'payment.format': 'Format du cours',
    'payment.recorded': 'Enregistré (À votre rythme)',
    'payment.online': 'En ligne (Sessions en direct)',
    'payment.onlineExtra': '+2 000 DA',
    'payment.startDate': 'Date de début',
    'payment.next': 'Continuer vers le paiement',
    'payment.back': 'Retour aux informations',
    'video.homework': 'Soumission des devoirs',
    'video.aiMentor': 'Mentor IA',
    'video.uploadHomework': 'Télécharger le devoir',
    'video.chatPlaceholder': 'Posez une question à votre mentor IA...',
    'video.markComplete': 'Marquer comme terminé',
    'video.completed': 'Terminé',
    'video.next': 'Leçon suivante',
    'course.back': 'Retour au cours',
    'course.lockedTitle': 'Ce contenu est verrouillé',
    'course.lockedDesc': 'Inscrivez-vous à ce cours pour débloquer tous les chapitres, exercices et devoirs.',
    'course.unlock': 'Débloquer le cours maintenant',
    'course.videoContent': 'Contenu vidéo pour le chapitre',
    'course.markComplete': 'Marquer comme terminé',
    'course.markedComplete': 'Leçon marquée comme terminée !',
    'course.about': 'À propos de ce',
    'course.task': 'Tâche',
    'course.expectedOutcome': 'Résultat attendu',
    'course.lessonDesc': 'Dans cette leçon, nous allons approfondir les concepts fondamentaux du chapitre',
    'course.submitWork': 'Soumettez votre travail',
    'course.upload': 'Cliquez ou faites glisser pour télécharger la vidéo',
    'course.needHelp': 'Besoin d\'aide ?',
    'course.helpDesc': 'Bloqué sur un exercice ou une question sur les devoirs ? Nos mentors sont là pour vous aider.',
    'course.contactSupport': 'Contacter le support',
    'course.session': 'Session',
    'course.exercise': 'Exercice',
    'course.homework': 'Devoir',
    'course.resources': 'Ressources',
    'ai.welcome': "Bonjour ! Je suis votre mentor IA. Téléchargez votre vidéo de devoir, et je l'examinerai pour vous donner une évaluation !",
    'ai.received': "Génial ! J'ai bien reçu votre vidéo. Donnez-moi un moment pour l'examiner...",
    'ai.mentor': 'Mentor IA',
    'ai.online': 'En ligne et prêt à examiner',
    'ai.ask': 'Demandez à votre mentor...',
    'ai.title': 'IA Cutscene',
    'ai.subtitle': 'Votre compagnon IA tout-en-un pour le montage vidéo.',
    'ai.chat': 'Chat',
    'ai.voice': 'Voix',
    'ai.generate': 'Générer',
    'ai.image': 'Image',
    'ai.video': 'Vidéo',
    'ai.music': 'Musique',
    'ai.uploadDoc': 'Télécharger un document',
    'ai.placeholder': 'Posez n\'importe quelle question sur le montage vidéo...',
    'ai.systemPrompt': 'Vous êtes IA Cutscene, un assistant spécialisé dans le montage vidéo et le motion design. Vous pouvez aider avec des questions techniques, des idées créatives et générer des ressources comme des images, des vidéos et de la musique. Vous devez UNIQUEMENT discuter de sujets liés au montage vidéo, au motion design, à la cinématographie et à la post-production. Si on vous interroge sur d\'autres sujets, redirigez poliment la conversation vers le montage vidéo.',
    'auth.welcomeBack': 'Bon retour',
    'auth.enterDetails': 'Veuillez entrer vos coordonnées pour vous connecter',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.signIn': 'Se connecter',
    'auth.orContinueWith': 'Ou continuer avec',
    'auth.noAccount': "Vous n'avez pas de compte ?",
    'auth.signUpFree': 'Inscrivez-vous gratuitement',
    'support.center': 'Centre de support',
    'support.title': 'Comment pouvons-nous vous aider ?',
    'support.desc': 'Notre équipe de support est là pour vous aider avec toutes vos questions ou problèmes. Contactez-nous via l\'un des canaux ci-dessous.',
    'support.emailTitle': 'Support par e-mail',
    'support.emailDesc': 'Pour les demandes générales et les questions de facturation.',
    'support.emailAction': 'Envoyer un e-mail',
    'support.whatsappTitle': 'Support WhatsApp',
    'support.whatsappDesc': 'Obtenez des réponses rapides à vos questions techniques.',
    'support.whatsappAction': 'Discuter maintenant',
    'support.phoneTitle': 'Support téléphonique',
    'support.phoneDesc': 'Disponible du dimanche au jeudi, de 9h à 17h.',
    'support.phoneAction': 'Appelez-nous',
    'support.sendMessage': 'Envoyez-nous un message',
    'support.formDesc': 'Vous avez une question spécifique ou un commentaire ? Remplissez le formulaire et notre équipe vous répondra dans les 24 heures.',
    'support.feature1': 'Support technique expert',
    'support.feature2': 'Temps de réponse rapides',
    'support.fullName': 'Nom complet',
    'support.namePlaceholder': 'Votre nom',
    'support.emailAddress': 'Adresse e-mail',
    'support.emailPlaceholder': 'Votre e-mail',
    'support.message': 'Message',
    'support.messagePlaceholder': 'Comment pouvons-nous vous aider ?',
    'support.send': 'Envoyer le message',
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos paramètres de compte et vos informations personnelles.',
    'profile.personalInfo': 'Informations personnelles',
    'profile.displayName': 'Nom d\'affichage',
    'profile.email': 'Adresse e-mail',
    'profile.password': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le nouveau mot de passe',
    'profile.updateBtn': 'Mettre à jour le profil',
    'profile.updating': 'Mise à jour...',
    'profile.success': 'Profil mis à jour avec succès !',
    'profile.error': 'Échec de la mise à jour du profil.',
    'profile.avatarTitle': 'Photo de profil',
    'profile.uploadAvatar': 'Télécharger une nouvelle photo',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.courses': 'الدورات',
    'nav.contact': 'اتصل بنا',
    'nav.dashboard': 'لوحة التحكم',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    'nav.ai': 'Cutscene AI',
    'hero.badge': 'ابتكر، صمم، ارتقِ',
    'hero.title1': 'حاب تتعلم',
    'hero.title2': 'مونتاج فيديو',
    'hero.title3': 'حلك عند',
    'hero.subtitle': 'انضم إلى مجتمعنا المتنامي الذي يضم أكثر من 330 طالباً وحوّل مسيرتك المهنية من خلال مناهجنا المتميزة والمصممة للعالم الحديث.',
    'hero.explore': 'استكشف الدورات',
    'hero.studentsWork': 'أعمال طلابنا',
    'stats.students': 'طالب',
    'stats.courses': 'دورات',
    'stats.workshops': 'ورشة عمل مجانية',
    'stats.certified': 'معتمد',
    'courses.title': 'دوراتنا',
    'courses.subtitle': 'بوابتك لإحداث التغيير.',
    'courses.seeAll': 'مشاهدة جميع الدورات',
    'courses.details': 'التفاصيل',
    'courses.getStarted': 'ابدأ الآن',
    'studentsWork.title': 'أعمال الطلاب',
    'studentsWork.subtitle': 'شاهد التحولات المذهلة. طلابنا ينتقلون من مبتدئين إلى صناع محتوى محترفين.',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.subtitle': 'تتبع رحلتك التعليمية وإدارة المحتوى الخاص بك.',
    'dashboard.enrolled': 'مسجل',
    'dashboard.certificates': 'الشهادات',
    'dashboard.yourCourses': 'دوراتك',
    'dashboard.continue': 'متابعة',
    'dashboard.progress': 'تقدم الدورة',
    'dashboard.completedLessons': 'الدروس المكتملة',
    'dashboard.uploadTitle': 'رفع فيديو المشروع',
    'dashboard.uploadPlaceholder': 'عنوان الفيديو (مثال: واجب الفصل الأول)',
    'dashboard.uploadBtn': 'اختر ملف الفيديو',
    'dashboard.uploading': 'جاري الرفع...',
    'dashboard.latestActivity': 'آخر النشاطات',
    'dashboard.streak': 'سلسلة التعلم',
    'dashboard.days': 'أيام متتالية',
    'dashboard.weeklyGoal': 'الهدف الأسبوعي',
    'dashboard.noActivity': 'لم يتم العثور على نشاطات حديثة.',
    'dashboard.noEnrollments': 'لم تسجل في أي دورة بعد.',
    'dashboard.browse': 'تصفح الدورات',
    'dashboard.certTitle': 'الشهادات',
    'dashboard.certEarned': 'الدورة مكتملة',
    'dashboard.viewCert': 'عرض الشهادة',
    'dashboard.noCert': 'أكمل دورة للحصول على شهادتك الأولى!',
    'course.level': 'المستوى',
    'course.duration': 'المدة',
    'course.learn': 'ماذا ستتعلم',
    'course.requirements': 'المتطلبات',
    'course.curriculum': 'منهج الدورة',
    'course.instructor': 'المدرب',
    'course.lastUpdated': 'آخر تحديث',
    'course.reviews': 'آراء الطلاب',
    'course.writeReview': 'اكتب تقييماً',
    'course.rating': 'التقييم',
    'course.submitReview': 'إرسال التقييم',
    'course.noReviews': 'لا توجد تقييمات بعد. كن أول من يشارك تجربته!',
    'course.locked': 'هذا المحتوى مقفل. يرجى التسجيل في الدورة للوصول إليه.',
    'payment.title': 'أكمل طلبك',
    'payment.subtitle': 'انضم إلى أكثر من 330 طالباً يتعلمون معنا بالفعل.',
    'payment.summary': 'ملخص الطلب',
    'payment.total': 'المبلغ الإجمالي',
    'payment.method': 'طريقة الدفع',
    'payment.pay': 'دفع',
    'payment.secure': 'عملية دفع آمنة ومشفرة',
    'payment.infoTitle': 'معلومات الطالب',
    'payment.infoSubtitle': 'يرجى تقديم بياناتك للتسجيل.',
    'payment.phone': 'رقم الهاتف',
    'payment.phonePlaceholder': 'مثال: 0550 00 00 00',
    'payment.format': 'نوع الدورة',
    'payment.recorded': 'مسجلة (تعلم ذاتي)',
    'payment.online': 'أونلاين (حصص مباشرة)',
    'payment.onlineExtra': '+2,000 دج',
    'payment.startDate': 'تاريخ البدء',
    'payment.next': 'المتابعة للدفع',
    'payment.back': 'العودة للمعلومات',
    'video.homework': 'تسليم الواجبات',
    'video.aiMentor': 'المدرب الذكي',
    'video.uploadHomework': 'رفع الواجب',
    'video.chatPlaceholder': 'اسأل مدربك الذكي عن هذا الدرس...',
    'video.markComplete': 'تحديد كمكتمل',
    'video.completed': 'مكتمل',
    'video.next': 'الدرس التالي',
    'course.back': 'العودة للدورة',
    'course.lockedTitle': 'هذا المحتوى مقفل',
    'course.lockedDesc': 'سجل في هذه الدورة لفتح جميع الفصول والتمارين والواجبات.',
    'course.unlock': 'افتح الدورة الآن',
    'course.videoContent': 'محتوى الفيديو للفصل',
    'course.markComplete': 'تحديد كمكتمل',
    'course.markedComplete': 'تم تحديد الدرس كمكتمل!',
    'course.about': 'حول هذا',
    'course.task': 'المهمة',
    'course.expectedOutcome': 'النتيجة المتوقعة',
    'course.lessonDesc': 'في هذا الدرس، سنتعمق في المفاهيم الأساسية للفصل',
    'course.submitWork': 'سلم عملك',
    'course.upload': 'انقر أو اسحب لرفع الفيديو',
    'course.needHelp': 'تحتاج مساعدة؟',
    'course.helpDesc': 'عالق في تمرين أو لديك سؤال حول الواجب؟ مدربونا هنا للمساعدة.',
    'course.contactSupport': 'اتصل بالدعم',
    'course.session': 'جلسة',
    'course.exercise': 'تمرين',
    'course.homework': 'واجب',
    'course.resources': 'المصادر',
    'ai.welcome': "مرحباً! أنا مدربك الذكي. ارفع فيديو الواجب الخاص بك، وسأقوم بمراجعته وتقييمه!",
    'ai.received': "رائع! لقد استلمت الفيديو الخاص بك. أمهلني لحظة لمراجعته...",
    'ai.mentor': 'المدرب الذكي',
    'ai.online': 'متصل وجاهز للمراجعة',
    'ai.ask': 'اسأل مدربك...',
    'ai.title': 'Cutscene AI',
    'ai.subtitle': 'رفيقك الذكي الشامل لمونتاج الفيديو.',
    'ai.chat': 'دردشة',
    'ai.voice': 'صوت',
    'ai.generate': 'توليد',
    'ai.image': 'صورة',
    'ai.video': 'فيديو',
    'ai.music': 'موسيقى',
    'ai.uploadDoc': 'رفع مستند',
    'ai.placeholder': 'اسأل أي شيء عن مونتاج الفيديو...',
    'ai.systemPrompt': 'أنت Cutscene AI، مساعد متخصص في مونتاج الفيديو وتصميم الحركة. يمكنك المساعدة في الأسئلة التقنية، والأفكار الإبداعية، وتوليد الأصول مثل الصور والفيديوهات والموسيقى. يجب عليك فقط مناقشة المواضيع المتعلقة بمونتاج الفيديو، وتصميم الحركة، والسينما، وما بعد الإنتاج. إذا سُئلت عن مواضيع أخرى، وجه المحادثة بلباقة للعودة إلى مونتاج الفيديو.',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.enterDetails': 'يرجى إدخال بياناتك لتسجيل الدخول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.rememberMe': 'تذكرني',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.signIn': 'تسجيل الدخول',
    'auth.orContinueWith': 'أو المتابعة باستخدام',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.signUpFree': 'سجل مجاناً',
    'support.center': 'مركز الدعم',
    'support.title': 'كيف يمكننا مساعدتك؟',
    'support.desc': 'فريق الدعم لدينا هنا لمساعدتك في أي أسئلة أو مشاكل قد تواجهها. اتصل بنا من خلال أي من القنوات أدناه.',
    'support.emailTitle': 'الدعم عبر البريد الإلكتروني',
    'support.emailDesc': 'للاستفسارات العامة وأسئلة الفواتير.',
    'support.emailAction': 'إرسال بريد إلكتروني',
    'support.whatsappTitle': 'الدعم عبر واتساب',
    'support.whatsappDesc': 'احصل على إجابات سريعة لأسئلتك التقنية.',
    'support.whatsappAction': 'دردش الآن',
    'support.phoneTitle': 'الدعم الهاتفي',
    'support.phoneDesc': 'متاح من الأحد إلى الخميس، من 9 صباحاً حتى 5 مساءً.',
    'support.phoneAction': 'اتصل بنا',
    'support.sendMessage': 'أرسل لنا رسالة',
    'support.formDesc': 'لديك سؤال محدد أو ملاحظة؟ املأ النموذج وسيقوم فريقنا بالرد عليك في غضون 24 ساعة.',
    'support.feature1': 'دعم تقني متخصص',
    'support.feature2': 'أوقات استجابة سريعة',
    'support.fullName': 'الاسم الكامل',
    'support.namePlaceholder': 'اسمك',
    'support.emailAddress': 'البريد الإلكتروني',
    'support.emailPlaceholder': 'بريدك الإلكتروني',
    'support.message': 'الرسالة',
    'support.messagePlaceholder': 'كيف يمكننا مساعدتك؟',
    'support.send': 'إرسال الرسالة',
    'profile.title': 'ملفي الشخصي',
    'profile.subtitle': 'إدارة إعدادات حسابك ومعلوماتك الشخصية.',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.displayName': 'اسم العرض',
    'profile.email': 'البريد الإلكتروني',
    'profile.password': 'كلمة مرور جديدة',
    'profile.confirmPassword': 'تأكيد كلمة المرور الجديدة',
    'profile.updateBtn': 'تحديث الملف الشخصي',
    'profile.updating': 'جاري التحديث...',
    'profile.success': 'تم تحديث الملف الشخصي بنجاح!',
    'profile.error': 'فشل تحديث الملف الشخصي.',
    'profile.avatarTitle': 'الصورة الشخصية',
    'profile.uploadAvatar': 'رفع صورة جديدة',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
